services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ely
    ports:
      - "5432:5432"
    volumes:
      - ely_pg_data:/var/lib/postgresql/data

volumes:
  ely_pg_data:
